### PR TITLE
add errata field

### PR DESCRIPTION
**Pull request by jetsaredim**

### CODE REVIEW

**Comment by DevoKun** [comment]
@Gergall , please review and approve.

**Comment by scottrick** [comment]
I'm curious what the motivation behind this addition is?  While I have hoped to have errata added to the json, I was hoping for something more along the lines of:
```
errata: [
  {
    errataName: "E1",
    errataImageUrl: "insert_old_card_image_url_here.jpg"
  }
]
```

I'm not sure how just having the errataVersion will be helpful.  The current format is not very expandable either, if we ever did want to add the image url.

**Comment by jetsaredim** [comment]
> I'm curious what the motivation behind this addition is? While I have hoped to have errata added to the json, I was hoping for something more along the lines of:
> 
> ```
> errata: [
>   {
>     errataName: "Original",
>     errataImageUrl: "insert_old_original_card_image_url_here.jpg"
>   },
>   {
>     errataName: "E1",
>     errataImageUrl: "insert_old_E1_card_image_url_here.jpg"
>   },
>   {
>     errataName: "E2",
>     errataImageUrl: "insert_old_E2_card_image_url_here.jpg"
>   }
> ]
> ```
> 
> I'm not sure how just having the errataVersion will be helpful. The current format is not very expandable either, if we ever did want to add the image url.

The idea was just to have scomp be able to search for errata.  I worked with @Gergall on it but I don't think the use case of showing the errata history was part of the thought process.  I really have zero care how it gets implemented, this just seemed like the simplest way to implement it.  Stemmed from a discussion on discord about errata being searchable in scomp.  It would not be hugely difficult to implement as you suggest if that's what people want.  Maybe that can be a V2 of this feature or something?

**Review by DevoKun — APPROVED** [review]

**Comment by scottrick** [comment]
I just don't see what this gives us that you can't get by looking at the card image.  Unless you think people are going to be searching to see all cards that have E2 or something like that

**Comment by jetsaredim** [comment]
> I just don't see what this gives us that you can't get by looking at the card image. Unless you think people are going to be searching to see all cards that have E2 or something like that

Not specifically E2, but just errata in general.  I know personally I was making a deck the other day and realized there were a couple cards that had errata slips for them just by randomly searching vkit for other stuff and it would have been very helpful to have been able to search the entire database from scomp.

**Comment by Gergall** [comment]
Use case 1: It was requested to add a the Scomp columns for "Current Errata Number" so that as soon as you search a card you can see if it has an errata without having to click and view the image.  Pretty small convenience but it was specifically requested.

Use case 2: We have someone who is now going to work on a more manual effort of supplementing errataVersion with more new fields like errataNotes and errataDate.

I see the value in doing an errata section with multiple subsections as scottrick has suggested.  It would be extremely easy to do a find-and-replace to swap out all the errataVersion: "E1" lines with the bigger structure scottrick has suggested.  We still won't have anything except the errataVersion for now, other stuff like errataImageUrl, errataNotes, and errataDate can be worked on later.

FIND-AND-REPLACE

```
errataVersion: "E1",

to

errata: [
  {
    errataVersion: "Original",
  },
  {
    errataVersion: "E1",
  },
]
```

The "Original" would never need notes or a date, but it would serve as a placeholder to provide an image URL in the future.  E1 would potentially have notes and a date.  The most recent errata in any given list does not require an image since it would match the current live image.

What do you think?

**Comment by jetsaredim** [comment]
> Use case 1: It was requested to add a the Scomp columns for "Current Errata Number" so that as soon as you search a card you can see if it has an errata without having to click and view the image. Pretty small convenience but it was specifically requested.
> 
> Use case 2: We have someone who is now going to work on a more manual effort of supplementing errataVersion with more new fields like errataNotes and errataDate.
> 
> I see the value in doing an errata section with multiple subsections as scottrick has suggested. It would be extremely easy to do a find-and-replace to swap out all the errataVersion: "E1" lines with the bigger structure scottrick has suggested. We still won't have anything except the errataVersion for now, other stuff like errataImageUrl, errataNotes, and errataDate can be worked on later.
> 
> FIND-AND-REPLACE
> 
> ```
> errataVersion: "E1",
> 
> to
> 
> errata: [
>   {
>     errataVersion: "Original",
>   },
>   {
>     errataVersion: "E1",
>   },
> ]
> ```
> 
> The "Original" would never need notes or a date, but it would serve as a placeholder to provide an image URL in the future. E1 would potentially have notes and a date. The most recent errata in any given list does not require an image since it would match the current live image.
> 
> What do you think?

Does that mean all card entries would get the "Original" version added while E1s would have two entries and E2s would have three?

**Comment by DevoKun** [comment]
## in regards to the json with errata versions:

A list of card versions has value. There are people online in the past who have asked about the history of a card.

The dictonary would need to look more like this:

```json
errata: [{
    version: "Original",
    gametext: "xxxxxxxxxxxxxxxxxxxxxxxx"
  },{
    version: "1",
    gametext: "xxxxxxxxxxxxxxxxxxxxxxxx"
  },{
    version: "2",
    gametext: "xxxxxxxxxxxxxxxxxxxxxxxx"
  }]
```

We do not today have different image urls for cards, only the latest versions. So including the image is a larger project that may not be feasible without a major initiative that I would question the value of.

## The inclusion of an Errata Version field has value:

People have asked the question: _"how can I find a list of all cards that have received errata?"_ This question is understandable since they would need to print off the slips for a deck if the card had been updated. The data point provides value, even as just a "true/false" boolean.

```json
errataVersion: "E1",
```

## Merging this addition

I am going to merge the pull request as-is as it does provide value and is a great contribution.

The errata dictionary concept should become a backlog item for future work. That errata dictionary would almost be more of a "historical" record.

**Comment by jetsaredim** [comment]
> 

The only issue I see with a straight changelog like this is that you'd need to track all the changes. While that's most often in the gametext, there are other attributes that can be changed over the course of time.  I'd note that there's a handful of cards that were errata'd to include the astromech or grabber icons or others where the lore or other core attributes were changed.

I'm not sure what downstream apps are expecting from these json files but I wonder if it would make sense to just track the older versions of a given card as separate card objects, keep the errata version field and have some other field that denotes a card object as being the active version.

**Comment by Gergall** [comment]
Agreed that it's not just gametext - hence my suggestion of errataNotes.

I have one concern with merging as is.  We're presumably going to update Scomp to read/report the errataVersion field now, and then later the structure of the data might change.

I think we may want to try to figure out our final structure before any Scomp work is done.

**Comment by jetsaredim** [comment]
This actually works now without any direct updates to scomp.  (ErrataVersion contains E = all errata, or you can do E1 or E2 to further refine.)  For now, it's probably fine until a more complete solution is designed.
image

**Comment by Gergall** [comment]
Okay.  I was referring to the addition of an Errata Version column in the results list as has been requested.  It could be coded one way now and then may break later.

**Comment by EchoBaseTrooper** [comment]
Let's move this conversation to the json channel in slack, please

**Pull request merged**
