### PR TITLE
Json alphabetization

### PR DESCRIPTION
**Pull request by scottrick**
This PR has two things:
* Alphabetizes all the json properties.  I've validated that the json is exactly the same as before, with one tiny change:  Profundity (AI) had the same id as regular Profundity, so a new id was created for the AI version.  The gempId is still the same.
* Added json schema for the set and card json files and updated the validation steps.  From what I can see, there isn't a way to enforce alphabetization of fields with json schema, unfortunately.  This should at least enforce the correct types and formatting.

### CODE REVIEW

**Comment by scottrick** [comment]
FYI:  I used https://github.com/josephburnett/jd to validate the json files are all the same before/after the alphabetization (minus the one change I mentioned).

**Comment by TheBuzzSaw** [comment]
I would add mention of this new rule to the `README` (in addition to updating the example JSON there to also comply).

**Comment by scottrick** [comment]
I updated the PR with improvements to the README.

**Comment by scottrick** [comment]
rebased

**Pull request merged**
