### PR TITLE
Minor Tweaks

### PR DESCRIPTION
**Pull request by ronhowe**
Fixed \/ in two cards.
Standardized on (Immune to Alter.) instead of [Immune to Alter.] for Effects that this way.
Changed Slave 1 to Slave I to be consistent with card image and card game text.
Fixed lore quote.

### CODE REVIEW

**Review by scottrick — APPROVED** [review]
Looks good to me!

**Comment by ronhowe** [comment]
Thoughts on a merge?

**Comment by scottrick** [comment]
I don't have permission to merge.

**Comment by DevoKun** [comment]
I do not know if these `[Immune to Alter.]` should be changed to `(Immune to Alter.)`
There seem to be some precedence in the json files that suggests that words enclosed in square brackets _(`[ ]`)_ have some keyword or programmatic significance.
Maybe @thomasmarlin can confirm if these changes are non-breaking.

**Comment by ronhowe** [comment]
I understand.  There are plenty of other Effects that already have (Immune to Alter.) though.

**Comment by thomasmarlin** [comment]
Nothing in the code programmatically looks for the square brackets.  I support moving all of these to be uniform.  That will make it much easier for users to search for that specific string.  If you don't mind, please go ahead and re-open this one and we can merge it

**Comment by ronhowe** [comment]
OK.  I'll start with a clean PR later today.

**Pull request closed without merging**
