### PR TITLE
emperors-prize

### PR DESCRIPTION
**Pull request by ronhowe**
Fixed Luke Skywalker Emperors Prize Properties

### CODE REVIEW

**Comment by thomasmarlin** [comment]
If you have a whole batch of changes, feel free to submit a bunch as a single PR.  I'm sure that will be easier on you, not needing to make so many branches an manage all of that mess. These contributions are awesome!

**Comment by thomasmarlin** [comment]
By the way, what is your username on the forums so I can give you a shout-out?

**Comment by ronhowe** [comment]
https://twitter.com/ronhowe
https://forum.starwarsccg.org/memberlist.php?mode=viewprofile&u=422 (ronhowe)
Puhg on the SWCCG Discord.

The reason I am easily finding all of these is I am writing a parser in PowerShell that converts the JSON files to CDF files for Holotable.  It's going really well and doing file diffs using Notepad++ are letting easily know where the Holotable repo CDF files are wrong, where the JSON repo  files are wrong, or my parser is wrong.  :)

https://github.com/ronhowe/holotable-tools

**Comment by ronhowe** [comment]
I prefer one PR at a time so I don't lose my marbles.  :)

**Comment by ronhowe** [comment]
It also takes me a bit of time to iterate each fix and re-parse and review.

**Pull request closed without merging**
