### PR TITLE
Pulled legacy cards out into their own Light/Dark-legacy.json files.

### PR DESCRIPTION
**Pull request by scottrick**

### CODE REVIEW

**Comment by ronhowe** [comment]
May I suggest LegacyLight.json and LegacyDark.json?

Or LightLegacy.json and DarkLegacy.json?

**Comment by scottrick** [comment]
Sure, that's fine with me.

**Comment by ronhowe** [comment]
Previously I had suggested we do this.

BUT... Devon has recently acquired ALL the legacy images for Holotable.  As such, it is more of a compelling story to actually *keep* these all within the same file.

I'm not in charge.  Just thought I would clarify that I'm kind of changing my toon now that we actually have images.

**Comment by scottrick** [comment]
I would still be in favor of splitting them apart.  It might also be worth pulling the Decipher cards out from the Virtual cards, but that's not something we have a large need to do right now.  

The main advantage of having them split apart is that both Scomp Link & Comlink will have less to download when a new version of the json file(s) is detected.  I think both programs work similarly and download the latest for each json file if the cached version is no longer up to date.  And because neither program cares at all about the legacy cards (currently), they don't have to download that extra data.  It's not a huge amount of data, but it does help especially on mobile.

Also, smaller json files are easier to diff and code review in git, IMO.

1)  Easier to manage with Git - do git diffs with smaller files.
2)

**Pull request merged**
